#
# THE STANDARD DFDL MAKEFILE -- DO NOT CHANGE OR MOVE THIS FILE
# This file is used to clean, make, or run all Daffodil parsers
#

all:	c

schema:
	bash -c "daffodil save-parser -s schema.dfdl.xsd parser.bin";

c:
	bash -c "daffodil generate c -s schema.dfdl.xsd .";
	$(MAKE) -C c

run:
	dfdltest.sh

clean:
	rm -rf *~ parser.bin ./c
