string = %x22 1*character %x22
; string = %c'"' 1*character %c'"'

character = ALPHA / DIGIT / punct / %x5C escchar
; character = ALPHA / DIGIT / punct / %c'\' escchar

escchar = %x62 / %x66 / %x6E / %x72 / %x74 / %x22 / %x5C / "/" / %x75 HEXDIG HEXDIG HEXDIG HEXDIG
; escchar = %c'b' / %c'f' / %c'n' / %c'r' / %c't' / %c'"' / %c'\' / %c'/' / %c'u' HEXDIG HEXDIG HEXDIG HEXDIG

punct = " " / "!" / %x23-2F / %x3A-40 / "[" / %x5D-60 / %x7B-7F
; punct = %c' ' / %c'!' / %c'#'-'/' / %c':'-'@' / %c'[' / %c']'-'`' / %c'{'-'~' / %x7F
